export class Userstories  {
  due_date!: string;
  due_date_reason!: string;
  due_date_status!: string;
  start_date_task!: string;
  end_date_task!: string;
  description!: string;
  description_html!: string;
  is_late!: boolean;
  neighbors!: {
    next: {};
    previous: {}
  };
  is_inProgress!: boolean;
  is_toCome!: boolean;
  is_noDatesTask!: boolean;
  total_comments!: number;
  tags!: string[];
  attachments!: string[];
  blocked_note_html!: string;
  status!: number;
  status_extra_info!: {
    name: string;
    color: string;
    is_closed: boolean;
  }
  assigned_to!: number;
  assigned_to_extra_info!: {
    username: string;
    full_name_display: string;
    photo: string;
    big_photo: string;
    gravater_id: string;
    is_active: boolean;
    id: number;
  }
  owner!: number;
  owner_extra_info!: {
    username: string;
    full_name_display: string;
    photo: string;
    big_photo: string;
    gravater_id: string;
    is_active: boolean;
    id: number;
  }
  is_watcher!: boolean;
  total_watchers!: number;
  is_voter!: boolean;
  total_voters!: number;
  project!: number;
  project_extra_info!: {
    name: string;
    slug: string;
    logo_small_url: string;
    id: number;
  }
  id!: string;
  ref!: number;
  milestone!: number;
  milestone_slug!: string;
  milestone_name!: string;
  is_closed!: boolean;
  points!: {}
  backlog_order!: number;
  spring_order!: number;
  kanban_order!: number;
  created_date!: string;
  modified_date!: string;
  finish_date!: string;
  subject!: string;
  client_requirement!: boolean;
  team_requirement!: boolean;
  generated_from_issue!: number;
  generated_from_task!: number;
  from_task_ref!: number;
  external_reference!: string[];
  tribe_gig!: number;
  version!: number;
  is_blocked!: boolean;
  blocked_note!: string;
  total_points!: number;
  comment!: string;
  origin_issue!: number;
  origin_task!: number;
  epics!: string;
  epics_order!: number;
  tasks!: [];
  total_attachments!: number;
  swimlane!: number;
  assigned_users!: number[];
}
